project_id = "qkappowfrpsrvmxrndrx"

[functions.create-checkout]
verify_jwt = false

[functions.fetch-meme-coins]
verify_jwt = false

[functions.birdeye-api]
verify_jwt = false

[functions.helius-api]
verify_jwt = false

[functions.sentiment-analysis]
verify_jwt = false

[functions.whale-alerts]
verify_jwt = false