// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkappowfrpsrvmxrndrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYXBwb3dmcnBzcnZteHJuZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTE0MTYsImV4cCI6MjA2OTU2NzQxNn0.90MfoVJCEuKJwz0P3BTKXHTHHXkF0LZudpc9540qgew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});